# app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emsp
  namespace: argocd
  annotations:
    # List of images to track
    argocd-image-updater.argoproj.io/image-list: my-app=ghcr.io/heweiming/emsp2/emsp
    argocd-image-updater.argoproj.io/my-app.update-strategy: digest
    argocd-image-updater.argoproj.io/my-app.allow-tags: "^[0-9a-f]{7,40}$"
    argocd-image-updater.argoproj.io/my-app.update-interval: 1m
spec:
  project: default
  source:
    repoURL: https://github.com/heweiming/my-k8s-configs.git
    targetRevision: main
    path: dev  # Path to YAML files (root of repo)
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true  # Auto-sync if changes are detected
      prune: true      # Clean up old resources
