apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    argocd-image-updater.argoproj.io/image-list: my-app=ghcr.io/heweiming/emsp2/emsp
    argocd-image-updater.argoproj.io/my-app.update-strategy: latest
 #   argocd-image-updater.argoproj.io/my-app.allow-tags: "^[0-9a-f]{7,40}$"
    argocd-image-updater.argoproj.io/my-app.update-interval: 1m
  labels:
    app: emsp
  name: emsp
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: emsp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: emsp
    spec:
      containers:
      - image: ghcr.io/heweiming/emsp2/emsp:7abd02c2fd210e5518752f5517c1d49c427ab09c
        imagePullPolicy: IfNotPresent
        name: emsp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

