apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    argocd-image-updater.argoproj.io/image-list: emsp=ghcr.io/heweiming/emsp2/emsp
    argocd-image-updater.argoproj.io/my-app.update-strategy: digest
  generation: 1
  labels:
    app: emsp
  name: emsp
  namespace: default
  resourceVersion: "1040"
  uid: 5bacde9b-6cba-4d40-af00-4fef5311f56d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: emsp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: emsp
    spec:
      containers:
      - image: ghcr.io/heweiming/emsp2/emsp
        imagePullPolicy: IfNotPresent
        name: emsp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

