apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-03-23T14:01:40Z"
  generation: 1
  labels:
    app: emsp
  name: emsp
  namespace: default
  resourceVersion: "1040"
  uid: 5bacde9b-6cba-4d40-af00-4fef5311f56d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: emsp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: emsp
    spec:
      containers:
      - image: sha256:85ee5c683bcd466053106ec79fdc8eb584556729e175999a0070295aa30420fb
        imagePullPolicy: IfNotPresent
        name: sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-03-23T14:01:41Z"
    lastUpdateTime: "2025-03-23T14:01:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-23T14:01:40Z"
    lastUpdateTime: "2025-03-23T14:01:41Z"
    message: ReplicaSet "emsp-86db46c847" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
