apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-03-23T14:02:48Z"
  labels:
    app: emsp
  name: emsp
  namespace: default
  resourceVersion: "11517"
  uid: 2d939575-32fc-4778-98e8-8bd4e7ac882f
spec:
  clusterIP: 10.110.239.255
  clusterIPs:
  - 10.110.239.255
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32357
    port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: emsp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
