apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emsp
  name: emsp
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: emsp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: emsp
    spec:
      containers:
      - image: ghcr.io/heweiming/emsp2/emsp:cca1fb4e5681a752c05fedf3265000d6756b6b51
        imagePullPolicy: Always
        name: emsp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

